# 端口
server:
  port: 9003

# sa-token配置
sa-token:
  # 打印操作日志
  is-log: true
#  # ⭐ 必须开启（关键）
#  alone-redis: true
  json-converter: jackson
  # sso-client 相关配置
  sso-client:
    # 应用标识
    client: sso-client3
    # sso-server 端主机地址
    server-url: http://sa-sso-server.com:9000
    # 使用 Http 请求校验 ticket (模式三)
    is-http: true
    # API 接口调用秘钥
    secret-key: SSO-C3-kQwIOrYvnXmSDkwEiFngrKidMcdrgKor

spring:
  data:
    # 配置 Redis 连接 （此处与 SSO-Server 端连接不同的 Redis）
    redis:
      # Redis数据库索引
      database: 3
      # Redis服务器地址
      host: 127.0.0.1
      # Redis服务器连接端口
      port: 6379
      # Redis服务器连接密码（默认为空）
      password:
      # 连接超时时间
      timeout: 10s

